# This yaml file is intended for users who wish to utilize the luh2.py tool on their own machines.
# The file is not yet tested regularly to determine if the latest versions of the dependencies will
# always work.  This regular testing is expected to be implemented in the future.
name: luh2
channels:
  - conda-forge
  - defaults
dependencies:
  - xesmf
  # xarray which is autodownloaded as xesmf dependency, uses scipy, which needs netcdf4 to open datasets
  - netcdf4
