module EDCLMLinkMod

  ! ============================================================================
  ! Modules to control the passing of infomation generated by ED into CLM to be used for either 
  ! diagnostics, or as input to the land surface components. 
  ! ============================================================================

  use shr_kind_mod     , only : r8 => shr_kind_r8
  use shr_infnan_mod, only : isnan => shr_infnan_isnan
  use decompMod        , only : bounds_type
  use clm_varpar       , only : numpft, numcft, mxpft
  use clm_varctl       , only : iulog 
  use ColumnType       , only : col
  use EDtypesMod       , only : ed_site_type, ed_cohort_type, ed_patch_type, ncwd
  use EDtypesMod       , only : sclass_ed, nlevsclass_ed, AREA, cp_nclmax, cp_nlevcan
  use CanopyStateType  , only : canopystate_type
  use clm_varctl       , only : use_vertsoilc
  use EDParamsMod      , only : ED_val_ag_biomass
  use SoilBiogeochemCarbonFluxType    , only : soilbiogeochem_carbonflux_type
  use SoilBiogeochemCarbonStatetype   , only : soilbiogeochem_carbonstate_type
  use clm_time_manager       , only : is_beg_curr_day, get_step_size, get_nstep
  use shr_const_mod, only: SHR_CONST_CDAY
  use abortutils      , only : endrun
  use shr_log_mod     , only : errMsg => shr_log_errMsg    
  use EDCanopyStructureMod, only : calc_areaindex

  !
  implicit none
  private
  !
  logical :: DEBUG = .false.  ! for debugging this module (EDCLMLinkMod.F90)
  
  ! !PUBLIC DATA MEMBERS 
  real(r8), public :: cwd_fcel_ed  
  real(r8), public :: cwd_flig_ed

  ! Public routines
  procedure , public  :: ed_clm_link
  
  ! Private routines
  procedure , private :: ed_clm_leaf_area_profile

  ! 10/30/09: Created by Rosie Fisher
  !-----------------------------------------------------------------------

contains

  !-----------------------------------------------------------------------

 

  !------------------------------------------------------------------------

  ! INTERF-TODO: THIS ROUTINE COULD BE SPLIT.  IT CALCULATES BOTH FATES/ED INTERNALS
  ! AS WELL AS VARIABLES FOR CLM/ALM.


 

  
  
end module EDCLMLinkMod
