name: Run unit tests with ctsm 

on:
  pull_request:

jobs:
  ctsm-unit-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ngeet/containers/unit-test-ctsm:latest
      env:
        TESTING_DIR: /CTSM/src/fates/testing/
        BRANCH_NAME: ${{ github.head_ref }}
        BRANCH_URL: ${{ github.event.pull_request.head.repo.html_url }}

    steps:
      - name: Checkout code with git-fleximod
        run: |
          cd /CTSM
          ./bin/git-fleximod update

      - name: Activate spack environment and run tests 
        run: |
          . /opt/spack-environment/activate.sh
          echo "NETCDF_FORTRAN_PATH: $NETCDF_FORTRAN_PATH"
          echo "NETCDF_C_PATH: $NETCDF_C_PATH"
          cd ${{env.TESTING_DIR}}
          python run_unit_tests.py --test-list fire_fuel


